/**
 * Generates formatted plain-text reports for WhatsApp sharing.
 */

function generatePlantReport(monthLabel, sections, metrics) {
  const lines = [];
  lines.push('═══════════════════════════════');
  lines.push('🏭 HBL ENGINEERING LIMITED');
  lines.push('MEC PLANT SUMMARY REPORT');
  lines.push(`📅 ${monthLabel}`);
  lines.push('═══════════════════════════════');
  lines.push('');
  lines.push(`📊 Overall Plant Score: ${metrics.plantScore}%`);
  lines.push(`⭐ Average 5S Score: ${metrics.avg5S}/5.0`);
  lines.push(`🔧 AM Closure: ${metrics.avgAMClosure}%`);
  lines.push(`📌 Abnormalities: ${metrics.totalAbnormalities} (Closed: ${metrics.closedAbnormalities})`);
  lines.push(`🔁 Repeated: ${metrics.repeatedAbnormalities}`);
  lines.push(`💡 Total Kaizens: ${metrics.totalKaizens}`);
  lines.push(`📈 Lean Projects: ${metrics.totalLeanProjects}`);
  lines.push(`🏅 ISO Progress: ${metrics.avgISO}%`);
  lines.push('');
  lines.push('📋 SUBMISSION STATUS');
  lines.push(`✅ Submitted: ${metrics.submittedSections}/13`);
  lines.push(`⏳ Pending: ${metrics.pendingSections}/13`);
  lines.push('');
  lines.push('─────────────────────────────');
  lines.push('SECTION WISE SUMMARY');
  lines.push('─────────────────────────────');

  for (const section of sections) {
    const statusIcon = section.status === 'submitted' ? '✅' : '⏳';
    lines.push(`${statusIcon} ${section.code}: 5S=${section.fiveS || 'N/A'} | AM=${section.amClosure || 0}% | Kaizens=${section.kaizens || 0}`);
  }

  lines.push('');
  lines.push('─────────────────────────────');
  lines.push('Generated by MEC Dashboard');
  lines.push(`🕐 ${new Date().toLocaleString('en-IN')}`);

  return lines.join('\n');
}

function generateSectionReport(sectionName, monthLabel, data) {
  const lines = [];
  lines.push('═══════════════════════════════');
  lines.push('🏭 HBL ENGINEERING LIMITED');
  lines.push(`MEC REPORT: ${sectionName}`);
  lines.push(`📅 ${monthLabel}`);
  lines.push('═══════════════════════════════');
  lines.push('');

  // 5S
  if (data.module_5s) {
    lines.push('⭐ 5S AUDIT');
    lines.push(`   Target: ${data.module_5s.target || 'N/A'} | Actual: ${data.module_5s.actual || 'N/A'}`);
    lines.push(`   Score: ${data.module_5s.audit_score || 'N/A'}`);
    lines.push('');
  }

  // AM
  if (data.module_am) {
    lines.push('🔧 AUTONOMOUS MAINTENANCE');
    lines.push(`   CLRI Target: ${data.module_am.clri_target || 0} | Completed: ${data.module_am.clri_completed || 0}`);
    lines.push(`   Closure: ${data.module_am.closure_pct || 0}%`);
    lines.push('');
  }

  // Abnormalities
  if (data.module_abnormalities) {
    const m = data.module_abnormalities;
    lines.push('📌 ABNORMALITIES');
    lines.push(`   White: ${m.white_tags || 0} | Red: ${m.red_tags || 0} | Total: ${m.total || 0}`);
    lines.push(`   Closed: ${m.closed || 0} | Pending: ${m.pending || 0}`);
    lines.push(`   Repeated: ${m.repeated || 0} | CAPA: ${m.capa_status || 'N/A'}`);
    lines.push('');
  }

  // Avinya
  if (data.module_avinya) {
    lines.push('👁️ AVINYA OBSERVATIONS');
    lines.push(`   Posted: ${data.module_avinya.observations_posted || 0} | Closed: ${data.module_avinya.closed || 0} | Pending: ${data.module_avinya.pending || 0}`);
    lines.push('');
  }

  // Kaizens
  if (data.module_kaizens) {
    lines.push('💡 KAIZENS');
    lines.push(`   Submitted: ${data.module_kaizens.submitted || 0} | Approved: ${data.module_kaizens.approved || 0} | Implemented: ${data.module_kaizens.implemented || 0}`);
    lines.push(`   Savings: ₹${(data.module_kaizens.savings || 0).toLocaleString('en-IN')}`);
    lines.push('');
  }

  // Lean
  if (data.module_lean_projects) {
    const l = data.module_lean_projects;
    lines.push('📈 LEAN PROJECTS');
    lines.push(`   QCC: ${l.qcc || 0} | SMED: ${l.smed || 0} | Kanban: ${l.kanban || 0}`);
    lines.push(`   Poka-Yoke: ${l.poka_yoke || 0} | VSM: ${l.vsm || 0} | Other: ${l.other_lean || 0}`);
    lines.push(`   Status: ${l.status || 'N/A'} | Completion: ${l.completion_pct || 0}%`);
    lines.push('');
  }

  // Process Std
  if (data.module_process_std) {
    lines.push('📋 PROCESS STANDARDISATION');
    lines.push(`   Findings: ${data.module_process_std.audit_findings || 0} | Closed: ${data.module_process_std.closed || 0} | Pending: ${data.module_process_std.pending || 0}`);
    lines.push('');
  }

  // ISO
  if (data.module_iso) {
    const i = data.module_iso;
    lines.push('🏅 ISO OBJECTIVES');
    lines.push(`   QMS: ${i.qms_current || 'N/A'}/${i.qms_target || 'N/A'} (${i.qms_status || 'N/A'})`);
    lines.push(`   EMS: ${i.ems_current || 'N/A'}/${i.ems_target || 'N/A'} (${i.ems_status || 'N/A'})`);
    lines.push(`   OHSAS: ${i.ohsas_current || 'N/A'}/${i.ohsas_target || 'N/A'} (${i.ohsas_status || 'N/A'})`);
    lines.push('');
  }

  lines.push('─────────────────────────────');
  lines.push('Generated by MEC Dashboard');
  lines.push(`🕐 ${new Date().toLocaleString('en-IN')}`);

  return lines.join('\n');
}

module.exports = { generatePlantReport, generateSectionReport };
